apiVersion: v1
kind: ConfigMap
metadata:
  name: expense-tracker-config
data:
  APP_ENV: "production"
  DB_HOST: "postgres-db.internal.cloud"
  DB_PORT: "5432"
  FEATURE_FLAG_ANALYTICS: "enabled"
########################################################################
#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: expense-tracker-config
#data:
 #APP_ENV: "production"
# DB_HOST: "postgres-db.internal.cloud"
# DB_PORT: "5432"
 #FEATURE_FLAG_ANALYTICS: "disabled" with this overall output is below
 ###########################################################
 #APP_ENV=production
#DB_HOST=postgres-db.internal.cloud
#FEATURE_FLAG_ANALYTICS=disabled
#FEATURE_FLAG_ANALYTICS: "enabled"  #Flag updated to enabled 
###############################################################################################################################
