apiVersion: apps/v1
kind: Deployment
metadata:
  name: expense-tracker-web
  labels:
    app: expense-tracker-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expense-tracker-web
  template:
    metadata:
      labels:
        app: expense-tracker-web
    spec:
      containers:
      - name: web
        # Replicate Scenario 3: Breaking & Fixing a Rolling Deployment
        image: asia-south1-docker.pkg.dev/project-3abb875e-b867-4aaf-843/expense-repo/expense-tracker-web:v2.0.0-broken
        ports:
        - containerPort: 8501
        resources:
          requests:
            memory: "128Mi"
            cpu: "5m"
          limits:
            memory: "256Mi"
            cpu: "10m"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 5
          periodSeconds: 5
