apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: expense-tracker-pvc
spec:
  accessModes:
    - ReadWriteOnce
  #storageClassName: invalid-fast-ssd-class  # ❌ INTENTIONAL FAULT: Non-existent StorageClass
  storageClassName: standard-rwd  # Scenario 8 fixed ✅ Fixed: Valid GKE StorageClass
  resources:
    requests:
      storage: 10Gi
