name: "Devops SRE Troubleshoot Question Practice"
on:
  workflow_dispatch:
jobs:
  run-troubleshoot-job:
     name: "Run the Workflow"
     runs-on: ubuntu-latest
     steps:
        - name: Test workflow
          run: echo "Hello Troubleshoot workflow"
